=== Yeojin0523/-study/webService/week03/BookML.dtd
<!ENTITY % dateAttribute "year CDATA #REQUIRED
					month (01|02|03|04|05|06|07|08|09|10|11|12) #REQUIRED
					day CDATA #REQUIRED"> <!-- #4, #6 -->
<!ENTITY % commonBookInfo_1 "title, author+, publisher, publishDate">
<!ENTITY % commonBookInfo_2 "price, pages+, rating+, coverArt?, bookIntroduction?, review?">
<!ENTITY % bookAttribute "id ID #REQUIRED
					 categories CDATA #REQUIRED">
<!ENTITY % ebookAttribute "format, size, period?"> <!-- (나)#2 기타 요구사항_내부 parameter entity 사용 -->
<!ENTITY publish "김영사"> <!-- (나)#2 기타 요구사항_내부 일반 parsed entity 사용-->

<!NOTATION gif PUBLIC "image/gif" "imageViewer.exe">
<!NOTATION jpeg PUBLIC "image/jpeg" "imageViewer.exe">

<!ELEMENT catalog (bookList, bookCategory)>
<!ELEMENT bookList (book*, ebook, newEbook)>

<!ELEMENT book (%commonBookInfo_1;, revisionDate*, %commonBookInfo_2;)> <!-- #1, #2 도서와 각 속성 정의-->
<!ATTLIST book %bookAttribute;> <!-- #3, #7 도서의 속성 정의하는데, entity로 묶음 -->
			
<!ELEMENT ebook (%commonBookInfo_1;, revisionDate*, %commonBookInfo_2;, %ebookAttribute;)> <!-- #9 -->
<!ATTLIST ebook %bookAttribute;>		

<!ELEMENT newEbook (%commonBookInfo_1;, %commonBookInfo_2;, %ebookAttribute;)> <!-- #11 -->
<!-- newEbook에서 중간 revisionDate값을 빼야 하니까 그 앞까지 하나로 묶고, 그 뒤까지 하나로 묶어서 entity로 가져오는 게 낫다 -->
<!ATTLIST newEbook %bookAttribute;>	

<!-- #10 -->
<!ELEMENT format (#PCDATA)>
<!ATTLIST format value (EPUB | PDF | StreamText | StreamImage) #REQUIRED>
<!ELEMENT size (#PCDATA)>
<!ATTLIST size unit (KB | MB) #REQUIRED>
<!ELEMENT period (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>

<!ELEMENT publishDate (#PCDATA)>
<!ATTLIST publishDate %dateAttribute;> 

<!ELEMENT revisionDate (#PCDATA)>
<!ATTLIST revisionDate %dateAttribute;>
<!-- 중복, 반복되는 부분을 entity로 정의해야 돼, parameter entity(dtd의 일부에 해당하는데 중복되는 부분 -->

<!ELEMENT price (listPrice, salesPrice)> 					
<!ATTLIST price currency (won|dollar|yen) "won"> <!-- #5 열거형으로 -->

<!ELEMENT listPrice (#PCDATA)>
<!ELEMENT salesPrice (#PCDATA)>
<!ATTLIST salesPrice discountRate CDATA #REQUIRED> <!-- 0이상 90 이하 가지려면? -->
<!ELEMENT pages (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

<!ELEMENT coverArt (#PCDATA)> <!-- #8 도서의 표지그림, 속성 -->
<!ATTLIST coverArt src CDATA #REQUIRED
						type NOTATION (gif | jpeg) "gif"> 

<!ELEMENT bookIntroduction (#PCDATA)>
<!ELEMENT review (#PCDATA)>

<!ELEMENT bookCategory (category*)>
<!--  <!ELEMENT category EMPTY> #7 -->
<!ELEMENT category (category*)> <!-- #12 category가 category 자신을 다시 속성으로 가지게 정의 -->
<!ATTLIST category cid CDATA #REQUIRED>
<!ATTLIST category name CDATA #REQUIRED>

=== Yeojin0523/-study/webService/week03/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "BookML.dtd" >
<catalog>
  <bookList>
    <book id ="isbn-895468000-3" categories="c101-1-1">
      <title>방금 떠나온 세계</title>
      <author>김초엽</author>
      <publisher>publisher</publisher>
      <publishDate year="2015" month="01" day="01">출판일</publishDate>
      <revisionDate year="2023" month="02" day="28"></revisionDate>
      <price currency="won">
        <listPrice>가격</listPrice>
        <salesPrice discountRate="10">salesPrice</salesPrice>
      </price>
      <pages>276</pages>
      <rating>10.0</rating>
      <coverArt src="https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791160406504.jpg"></coverArt>
      <bookIntroduction>책소개</bookIntroduction>
      <review>책 리뷰</review>
    </book>
    <ebook id="isbn-9788934971351" categories="c102-1">
    	<title>철학은 날씨를 바꾼다.</title>
    	<author>서동욱</author>
    	<publisher>&publish;</publisher> <!-- (나)#3 built-in entity 사용-->
    	<publishDate year="2012" month="03" day="01"></publishDate>
    	<revisionDate year="2024" month="04" day="17"></revisionDate>
    	<price currency="won">
    		<listPrice>10000</listPrice>
    		<salesPrice discountRate="20"></salesPrice>
    	</price>
    	<pages>343</pages>
    	<rating>9.8</rating>
    	<coverArt src="https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788934971351.jpg"></coverArt>
    	<bookIntroduction>하하</bookIntroduction>
    	<review>이동진 책 추천으로 구매합니다</review>
    	<format value="PDF"></format>
    	<size unit="MB"></size>
    </ebook>
    <newEbook id="isbn-9788954675338" categories="c102-1">
    	<title>&lt;복자에게&gt;</title> <!-- (나)#3 기타 요구사항_built in entity 한 번 이상 사용함 -->
    	<author>김금희</author>
    	<publisher>문학동네</publisher>
    	<publishDate year="2012" month="03" day="01"></publishDate>
    	<price currency="won">
    		<listPrice>100</listPrice>
    		<salesPrice discountRate="20"></salesPrice>
    	</price>
    	<pages>44</pages>
    	<rating>9.0</rating>
    	<coverArt src="https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788954674492.jpg"></coverArt>
    	<bookIntroduction>책소개</bookIntroduction>
    	<review>구매합니다</review>
    	<format value="PDF"></format>
    	<size unit="MB"></size>
    </newEbook>
  </bookList>
  <bookCategory>
    <category cid="c101" name="문학">
    	<category cid="c101-1" name="소설"></category>
    	<category cid="c101-1-1" name="한국소설"></category>
  	</category>
  	<category cid="c102" name="인문">
  		<category cid="c102-1" name="철학"></category>
  	</category>
</bookCategory>
</catalog>
